In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

In [2]:
df=pd.read_csv('/content/student-mat.csv',sep=';')

In [3]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()

In [8]:
catergorical=df.select_dtypes(include='object').columns

In [9]:
print(catergorical)

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [10]:
for i in catergorical:
  df[i]=le.fit_transform(df[i])

In [11]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,0,0,18,1,0,0,4,4,0,4,...,4,3,4,1,1,3,6,5,6,6
1,0,0,17,1,0,1,1,1,0,2,...,5,3,3,1,1,3,4,5,5,6
2,0,0,15,1,1,1,1,1,0,2,...,4,3,2,2,3,3,10,7,8,10
3,0,0,15,1,0,1,4,2,1,3,...,3,2,2,1,1,5,2,15,14,15
4,0,0,16,1,0,1,3,3,2,2,...,4,3,2,1,2,5,4,6,10,10

In [13]:
x=df.drop('G3',axis=1)
y=df['G3']

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [18]:
model=Sequential([
Input(shape=(32,)),
Dense(128,activation='relu'),
Dense(64,activation='relu'),
Dense(32,activation='relu'),
Dense(1,activation='relu')])

In [19]:
model.compile(optimizer='adam',loss='mse',metrics=['r2_score'])

In [20]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 4s 102ms/step - loss: 106.0553 - r2_score: -4.5077 - val_loss: 86.0273 - val_r2_score: -2.1182
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 63.3281 - r2_score: -2.2888 - val_loss: 45.3750 - val_r2_score: -0.6447
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24.0848 - r2_score: -0.2508 - val_loss: 24.5259 - val_r2_score: 0.1110
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 13.7966 - r2_score: 0.2835 - val_loss: 22.3944 - val_r2_score: 0.1883
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 9.2541 - r2_score: 0.5194 - val_loss: 14.2499 - val_r2_score: 0.4835
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 6.7303 - r2_score: 0.6505 - val_loss: 12.2325 - val_r2_score: 0.5566
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 5.6734 - r2_score: 0.7054 - val_loss: 11.6788 - val_r2_score: 0.5767
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 4.9211 - r2_score: 0.7444 - val_loss: 11.0869 - val_r2_score: 0.5981
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4.4191 - r2_score: 0.7705 - val_loss: 10.6047 - val_r2_score: 0.6156
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0558 - r2_score: 0.7894 - val_loss: 10.5660 - val_r2_score: 0.6170
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.7085 - r2_score: 0.8074 - val_loss: 10.2867 - val_r2_score: 0.6271
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4393 - r2_score: 0.8214 - val_loss: 10.0768 - val_r2_score: 0.6348
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.2164 - r2_score: 0.8330 - val_loss: 10.1954 - val_r2_score: 0.6305
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9762 - r2_score: 0.8454 - val_loss: 9.9538 - val_r2_score: 0.6392
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.7487 - r2_score: 0.8573 - val_loss: 9.8588 - val_r2_score: 0.6427
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5412 - r2_score: 0.8680 - val_loss: 9.9483 - val_r2_score: 0.6394
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3713 - r2_score: 0.8769 - val_loss: 9.6451 - val_r2_score: 0.6504
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.2244 - r2_score: 0.8845 - val_loss: 9.5678 - val_r2_score: 0.6532
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0551 - r2_score: 0.8933 - val_loss: 9.5950 - val_r2_score: 0.6522
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.9104 - r2_score: 0.9008 - val_loss: 9.3508 - val_r2_score: 0.6611
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.7720 - r2_score: 0.9080 - val_loss: 9.4017 - val_r2_score: 0.6592
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6467 - r2_score: 0.9145 - val_loss: 9.3071 - val_r2_score: 0.6627
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5305 - r2_score: 0.9205 - val_loss: 9.2049 - val_r2_score: 0.6664
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4285 - r2_score: 0.9258 - val_loss: 9.1860 - val_r2_score: 0.6670
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.3178 - r2_score: 0.9316 - val_loss: 9.0395 - val_r2_score: 0.6724
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2367 - r2_score: 0.9358 - val_loss: 8.9447 - val_r2_score: 0.6758
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1458 - r2_score: 0.9405 - val_loss: 8.9233 - val_r2_score: 0.6766
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0586 - r2_score: 0.9450 - val_loss: 8.9159 - val_r2_score: 0.6768
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9904 - r2_score: 0.9486 - val_loss: 8.8281 - val_r2_score: 0.6800
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9153 - r2_score: 0.9525 - val_loss: 8.8550 - val_r2_score: 0.6790
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8463 - r2_score: 0.9561 - val_loss: 8.8168 - val_r2_score: 0.6804
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7791 - r2_score: 0.9595 - val_loss: 8.7239 - val_r2_score: 0.6838
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7247 - r2_score: 0.9624 - val_loss: 8.7058 - val_r2_score: 0.6844
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6611 - r2_score: 0.9657 - val_loss: 8.7746 - val_r2_score: 0.6820
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6061 - r2_score: 0.9685 - val_loss: 8.6746 - val_r2_score: 0.6856
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5544 - r2_score: 0.9712 - val_loss: 8.6264 - val_r2_score: 0.6873
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5159 - r2_score: 0.9732 - val_loss: 8.7021 - val_r2_score: 0.6846
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4675 - r2_score: 0.9757 - val_loss: 8.5563 - val_r2_score: 0.6899
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4282 - r2_score: 0.9778 - val_loss: 8.5870 - val_r2_score: 0.6888
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3908 - r2_score: 0.9797 - val_loss: 8.5758 - val_r2_score: 0.6892
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3563 - r2_score: 0.9815 - val_loss: 8.6091 - val_r2_score: 0.6880
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3255 - r2_score: 0.9831 - val_loss: 8.6043 - val_r2_score: 0.6881
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2979 - r2_score: 0.9845 - val_loss: 8.5622 - val_r2_score: 0.6896
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2679 - r2_score: 0.9861 - val_loss: 8.5497 - val_r2_score: 0.6901
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2519 - r2_score: 0.9869 - val_loss: 8.5264 - val_r2_score: 0.6909
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2338 - r2_score: 0.9879 - val_loss: 8.7415 - val_r2_score: 0.6832
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2140 - r2_score: 0.9889 - val_loss: 8.5768 - val_r2_score: 0.6891
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1840 - r2_score: 0.9904 - val_loss: 8.6429 - val_r2_score: 0.6867
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1661 - r2_score: 0.9914 - val_loss: 8.6359 - val_r2_score: 0.6870
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1506 - r2_score: 0.9922 - val_loss: 8.4943 - val_r2_score: 0.6921
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1379 - r2_score: 0.9928 - val_loss: 8.6615 - val_r2_score: 0.6861
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1237 - r2_score: 0.9936 - val_loss: 8.6340 - val_r2_score: 0.6870
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1083 - r2_score: 0.9944 - val_loss: 8.5933 - val_r2_score: 0.6885
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0991 - r2_score: 0.9949 - val_loss: 8.6474 - val_r2_score: 0.6866
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0900 - r2_score: 0.9953 - val_loss: 8.6617 - val_r2_score: 0.6860
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0811 - r2_score: 0.9958 - val_loss: 8.5644 - val_r2_score: 0.6896
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0750 - r2_score: 0.9961 - val_loss: 8.5961 - val_r2_score: 0.6884
Epoch 58/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0664 - r2_score: 0.9965 - val_loss: 8.7229 - val_r2_score: 0.6838
Epoch 59/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0611 - r2_score: 0.9968 - val_loss: 8.5896 - val_r2_score: 0.6887
Epoch 60/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0575 - r2_score: 0.9970 - val_loss: 8.6741 - val_r2_score: 0.6856
Epoch 61/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0481 - r2_score: 0.9975 - val_loss: 8.6634 - val_r2_score: 0.6860
Epoch 62/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0448 - r2_score: 0.9977 - val_loss: 8.6896 - val_r2_score: 0.6850
Epoch 63/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0397 - r2_score: 0.9979 - val_loss: 8.7095 - val_r2_score: 0.6843
Epoch 64/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0355 - r2_score: 0.9982 - val_loss: 8.7019 - val_r2_score: 0.6846
Epoch 65/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0322 - r2_score: 0.9983 - val_loss: 8.6393 - val_r2_score: 0.6869
Epoch 66/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0286 - r2_score: 0.9985 - val_loss: 8.7734 - val_r2_score: 0.6820
Epoch 67/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0271 - r2_score: 0.9986 - val_loss: 8.7191 - val_r2_score: 0.6840
Epoch 68/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0234 - r2_score: 0.9988 - val_loss: 8.6937 - val_r2_score: 0.6849
Epoch 69/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0213 - r2_score: 0.9989 - val_loss: 8.6620 - val_r2_score: 0.6860
Epoch 70/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0190 - r2_score: 0.9990 - val_loss: 8.7450 - val_r2_score: 0.6830
Epoch 71/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0170 - r2_score: 0.9991 - val_loss: 8.6894 - val_r2_score: 0.6850
Epoch 72/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0154 - r2_score: 0.9992 - val_loss: 8.7225 - val_r2_score: 0.6838
Epoch 73/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0138 - r2_score: 0.9993 - val_loss: 8.7473 - val_r2_score: 0.6829
Epoch 74/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0124 - r2_score: 0.9994 - val_loss: 8.7014 - val_r2_score: 0.6846
Epoch 75/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0113 - r2_score: 0.9994 - val_loss: 8.7209 - val_r2_score: 0.6839
Epoch 76/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0103 - r2_score: 0.9995 - val_loss: 8.7125 - val_r2_score: 0.6842
Epoch 77/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0092 - r2_score: 0.9995 - val_loss: 8.7455 - val_r2_score: 0.6830
Epoch 78/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0082 - r2_score: 0.9996 - val_loss: 8.7553 - val_r2_score: 0.6827
Epoch 79/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0073 - r2_score: 0.9996 - val_loss: 8.7271 - val_r2_score: 0.6837
Epoch 80/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0064 - r2_score: 0.9997 - val_loss: 8.7359 - val_r2_score: 0.6834
Epoch 81/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - r2_score: 0.9997 - val_loss: 8.7587 - val_r2_score: 0.6825
Epoch 82/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - r2_score: 0.9997 - val_loss: 8.7528 - val_r2_score: 0.6827
Epoch 83/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0048 - r2_score: 0.9998 - val_loss: 8.7382 - val_r2_score: 0.6833
Epoch 84/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0043 - r2_score: 0.9998 - val_loss: 8.7459 - val_r2_score: 0.6830
Epoch 85/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0039 - r2_score: 0.9998 - val_loss: 8.7415 - val_r2_score: 0.6832
Epoch 86/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0037 - r2_score: 0.9998 - val_loss: 8.7456 - val_r2_score: 0.6830
Epoch 87/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032 - r2_score: 0.9998 - val_loss: 8.7386 - val_r2_score: 0.6833
Epoch 88/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0029 - r2_score: 0.9998 - val_loss: 8.7524 - val_r2_score: 0.6828
Epoch 89/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - r2_score: 0.9999 - val_loss: 8.7754 - val_r2_score: 0.6819
Epoch 90/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - r2_score: 0.9999 - val_loss: 8.7639 - val_r2_score: 0.6823
Epoch 91/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - r2_score: 0.9999 - val_loss: 8.7583 - val_r2_score: 0.6825
Epoch 92/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0019 - r2_score: 0.9999 - val_loss: 8.7640 - val_r2_score: 0.6823
Epoch 93/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0017 - r2_score: 0.9999 - val_loss: 8.7459 - val_r2_score: 0.6830
Epoch 94/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0017 - r2_score: 0.9999 - val_loss: 8.7481 - val_r2_score: 0.6829
Epoch 95/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - r2_score: 0.9999 - val_loss: 8.7460 - val_r2_score: 0.6830
Epoch 96/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0012 - r2_score: 0.9999 - val_loss: 8.7787 - val_r2_score: 0.6818
Epoch 97/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0011 - r2_score: 0.9999 - val_loss: 8.7756 - val_r2_score: 0.6819
Epoch 98/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.4772e-04 - r2_score: 1.0000 - val_loss: 8.7670 - val_r2_score: 0.6822
Epoch 99/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.0697e-04 - r2_score: 1.0000 - val_loss: 8.7533 - val_r2_score: 0.6827
Epoch 100/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.2915e-04 - r2_score: 1.0000 - val_loss: 8.7659 - val_r2_score: 0.6823

In [21]:
predict=model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

In [25]:
from sklearn.metrics import r2_score

In [26]:
print(r2_score(y_test,predict))

0.6822655200958252